### PR TITLE
Kokkos benchmark

### PR DESCRIPTION
**Pull request by drreynolds**
Pull request that:

1. Fixes multiple errors in the RAJA-based advection_reaction_3D benchmark program.
2. Creates a Kokkos-based advection_reaction_3D benchmark program.
3. Creates a simple CVODE+Kokkos example that uses 2D Kokkos views to more naturally work with multi-dimensional problem data.

### CODE REVIEW

**Comment by gardner48** [comment]
Maybe splitting the PR into one for RAJA fixes and one for the addition of Kokkos could work but I'd guess this would be more trouble than it's worth.

**Comment by drreynolds** [comment]
That could fix the GitHub UI issue, but may require that we approve/merge the RAJA PR before we issue the Kokkos PR.  If you guys want that, just let me know.

**Comment by balos1** [comment]
@drreynolds I think separating the PR is the best option. Also, please use the `feature/` prefix as we have CI rules based off of it.

**Comment by drreynolds** [comment]
Closing this PR in favor of the separate-PR approach.  I've just submitted a PR specific to the RAJA fixes.  Once that is merged, I'll submit a PR for the Kokkos work.

**Pull request closed without merging**
