### PR TITLE
CI (mingw): Install and build with SuiteSparse library

### PR DESCRIPTION
**Pull request by mmuetzel**
MSYS2 follows a rolling release model. I.e., most of its packages are quite new most of the time.
Adding the SuiteSparse libraries in the CI tests for MSYS2 might help to detect potentially API changes early.

### CODE REVIEW

**Comment by mmuetzel** [comment]
> @mmuetzel Can you sign your commit as mentioned [in the contributing guide](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md)?

I rebased on a current head of the `develop` branch and added the Signed-off-by at the end of the commit message.
Is that correct?

**Comment by balos1** [comment]
> > @mmuetzel Can you sign your commit as mentioned [in the contributing guide](https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md)?
> 
> I rebased on a current head of the `develop` branch and added the Signed-off-by at the end of the commit message. Is that correct?

Yes, it looks good now.

**Comment by mmuetzel** [comment]
It looks like the CI failed because GCC 14 is stricter when it comes to automatically converting pointer types than previous versions.
That is probably worth fixing independently.

**Comment by mmuetzel** [comment]
I opened #477 which hopefully addresses that issue.
(IIUC, that is a real issue indeed if `SUNDIALS_INT64_T` is defined on Windows or other platforms that use an LLP64 data model.)

**Review by balos1 — APPROVED** [review]

**Pull request merged**
