### PR TITLE
Fix soversion ?

### PR DESCRIPTION
**Pull request by jschueller**
some libs are missing soversion, and this causes clients libs to link against full version instead:
xref https://github.com/conda-forge/assimulo-feedstock/issues/88
this doesnt look intentional because matching soversion macros are actually defined

cc @gardner48 @jmrohwer

### CODE REVIEW

**Comment by balos1** [comment]
Yep, this seems to be a typo in the CMake. Thanks for opening the PR, its greatly appreciated!  Could you add a note to the CHANGELOG and sign the commit as per https://github.com/LLNL/sundials/blob/main/CONTRIBUTING.md?

**Comment by jschueller** [comment]
done

**Review by balos1 — APPROVED** [review]

**Review by balos1 — APPROVED** [review]

**Comment by jschueller** [comment]
@balos1 would it be possible to backport this patch into the next point release if any ?
Sadly it was not part of 6.6.2 version

**Comment by balos1** [comment]
@jschueller We are planning to do so, yes. It was missed in 6.6.2 unfortunately.

**Pull request merged**
