### PR TITLE
Do not include klu.h if already included by user

### PR DESCRIPTION
**Pull request by carlodefalco**
* include/sunlinsol/sunlinsol_klu.h : check whether klu.h was already included
  by user before including it

Signed-off-by: Carlo de Falco <carlo.defalco@polimi.it>

### CODE REVIEW

**Comment by carlodefalco** [comment]
In the discussion about a previous [pull request](https://github.com/LLNL/sundials/pull/10) I suggested this change here would probably be a simpler solution to the same problem.

Here I am submitting the suggested change in the form of a pull request.

**Comment by balos1** [comment]
We are accepting the changes in this pull request, but since our Github repository is currently just snapshots of our releases I cannot merge it here. I will download the PR as a patch and apply it to our development repository. 

The patch will be included in the SUNDIALS release which will occur in the next couple of weeks.

Thank you for your contribution!

**Comment by balos1** [comment]
Reopening this until the patch makes it into this repository.

**Comment by balos1** [comment]
The 4.1.0 release includes this fix. Closing the PR now.

**Pull request closed without merging**
