### PR TITLE
Update the ginkgo batched solvers interface

### PR DESCRIPTION
**Pull request by pratikvn**
This PR updates the existing (now old) ginkgo batched matrix format and solver interface with the new one that we already have in Ginkgo develop.

I put the base as `feature/ginkgo-batched`, but let me know if you would rather have it merged into your develop, but then I would need to rebase my branch on your develop.

This is still a WIP, as I am mostly co-developing kernels and features needed here in Ginkgo as well. See Ginkgo PR https://github.com/ginkgo-project/ginkgo/pull/1528, but I think this PR can already be looked at.

### CODE REVIEW

**Comment by balos1** [comment]
@pratikvn Are there further updates needed now that https://github.com/ginkgo-project/ginkgo/pull/1528 is merged?

**Comment by pratikvn** [comment]
@balos1, I made a couple of updates and can confirm that all Ginkgo tests pass with both reference and CUDA enabled. But I run into a weird error when enabling OpenMP:

```sh
CMakeFiles/test_sunlinsol_ginkgo_block.OMP.dir/test_sunlinsol_ginkgo_block.cpp.o: In function `main':    
tmpxft_0007f576_00000000-6_test_sunlinsol_ginkgo_block.cudafe1.cpp:(.text+0x79c): undefined reference to `N_VNew_Serial'
collect2: error: ld returned 1 exit status                                                               
make[2]: *** [examples/sunlinsol/ginkgo/CMakeFiles/test_sunlinsol_ginkgo_block.OMP.dir/build.make:114: examples/sunlinsol/ginkgo/test_sunlinsol_ginkgo_block.OMP] Error 1
make[1]: *** [CMakeFiles/Makefile2:9983: examples/sunlinsol/ginkgo/CMakeFiles/test_sunlinsol_ginkgo_block.OMP.dir/all] Error 2
```

Do you know the issue might be ?

**Comment by balos1** [comment]
Looks like `sundials_nvecserial` should be added here https://github.com/LLNL/sundials/blob/ae8f5b7dce890f2e330c2478c938bf92d7486a4a/cmake/macros/SundialsAddExamplesGinkgo.cmake#L96.

**Comment by pratikvn** [comment]
Thanks! That seems to work. Feel free to try this out with the latest Ginkgo develop and let me know if you face any issues.

**Review by balos1 — COMMENTED** [review]
Approved.

**Pull request merged**
