### PR TITLE
Fix build given explicit SUPERLUMT_LIBRARY_DIR

### PR DESCRIPTION
**Pull request by tbrk**
This patch seems to be needed to build Sundials (since 3.x) on Debian when
Superlu_MT is installed in `/usr/local/lib`, see the Dockerfile:
https://github.com/inria-parkas/sundialsml/blob/master/misc/Dockerfile-4.0.2

### CODE REVIEW

**Comment by balos1** [comment]
We would like to accept these changes, however, can you amend the commit message to include the line (substituting your name and email of course):
```
Signed-off-by: Jane Doe <jdoe@address.com>
```

You can do this automatically by doing `git commit -s`.

**Comment by tbrk** [comment]
No problem. Done. Thanks.

**Comment by balos1** [comment]
Do you have a build log associated with the failure if the patch is not included?

**Comment by tbrk** [comment]
Here is a `Dockerfile` without the patch:
```
FROM debian:stable
ENV SUNDIALSML_SRC=https://raw.githubusercontent.com/inria-parkas/sundialsml/master\
 SUPERLUMT_TARGZ=http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_mt_3.1.tar.gz\
 SUNDIALS_GIT=https://github.com/LLNL/sundials.git\
 SUNDIALS_TAG=v4.0.2\
 BUILDDIR=/root
USER root
RUN apt-get update\
 && apt-get install -y\
      cmake liblapack-dev libopenmpi-dev openmpi-bin libsuitesparse-dev python\
      wget csh patch git\
      pkg-config m4\
 && rm -rf /var/lib/apt/lists/*
RUN wget -qO- $SUPERLUMT_TARGZ | tar xz -C $BUILDDIR\
 && wget -qO- $SUNDIALSML_SRC/misc/superlu_mt_3.1.patch\
	| patch -d $BUILDDIR/SuperLU_MT_3.1 -p1\
 && make -C $BUILDDIR/SuperLU_MT_3.1 install lib\
 && mkdir -p /usr/local/include/superlu_mt\
 && cp $BUILDDIR/SuperLU_MT_3.1/SRC/*.h /usr/local/include/superlu_mt/\
 && cp $BUILDDIR/SuperLU_MT_3.1/lib/* /usr/local/lib/\
 && rm -rf $BUILDDIR/SuperLU_MT_3.1
RUN git -c advice.detachedHead=false\
 clone $SUNDIALS_GIT --branch $SUNDIALS_TAG --depth 1 $BUILDDIR/sundials\
 && mkdir $BUILDDIR/sundials-build\
 && printf "#!/bin/sh\n\
cmake -Wno-dev \$BUILDDIR/sundials\\\\\n\
 -DCMAKE_BUILD_TYPE=Release\\\\\n\
 -DOPENMP_ENABLE=1\\\\\n\
 -DMPI_ENABLE=1\\\\\n\
 -DBLAS_ENABLE=1\\\\\n\
 -DPTHREAD_ENABLE=1\\\\\n\
 -DEXAMPLES_ENABLE_C=1\\\\\n\
 -DKLU_ENABLE=1\\\\\n\
 -DKLU_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu\\\\\n\
 -DKLU_INCLUDE_DIR=/usr/include/suitesparse\\\\\n\
 -DSUPERLUMT_ENABLE=1\\\\\n\
 -DSUPERLUMT_THREAD_TYPE=PTHREAD\\\\\n\
 -DSUPERLUMT_LIBRARY_DIR=/usr/local/lib\\\\\n\
 -DSUPERLUMT_INCLUDE_DIR=/usr/local/include/superlu_mt\\\\\n\
 -DSUPERLUMT_LIBRARIES=-lblas\n" > /root/run-sundials-cmake\
 && chmod ugo+x /root/run-sundials-cmake
WORKDIR $BUILDDIR/sundial-build
RUN /root/run-sundials-cmake\
 && make -j\
 && make install
ENV LD_LIBRARY_PATH=/usr/local/lib
```

The Sundials `cmake` gives:
```
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
Appending C release flags
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Using int64_t for indices
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- The Fortran compiler identification is GNU 6.3.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
Appending Fortran release flags
-- Determining Fortran name-mangling scheme... OK
-- Check for working MPI C compiler: /usr/bin/cc
-- Check for working MPI C compiler: /usr/bin/cc -- broken
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- Checking for MPI-2 support... OK
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Using Pthreads
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- A library with BLAS API found.
-- Looking for BLAS libraries... OK
-- Checking if BLAS works... OK
-- Looking for SUPERLUMT libraries... OK
-- Checking if SUPERLUMT works... FAILED
CMake Warning at config/SundialsCMakeMacros.cmake:83 (MESSAGE):
  ------------------------------------------------------------------------

  WARNING: SUPERLUMT not functional - support will not be provided

  Double check spelling specified libraries (search is case sensitive)

  ------------------------------------------------------------------------
Call Stack (most recent call first):
  CMakeLists.txt:1003 (PRINT_WARNING)


-- Looking for KLU libraries...
-- Checking if KLU works... OK
-- Added NVECTOR_SERIAL module
-- Added SUNMATRIX_DENSE module
-- Added SUNMATRIX_BAND module
-- Added SUNMATRIX_SPARSE module
-- Added SUNLINSOL_BAND module
-- Added SUNLINSOL_DENSE module
-- Added SUNLINSOL_KLU module
-- Added SUNLINSOL_SPGMR module
-- Added SUNLINSOL_SPFGMR module
-- Added SUNLINSOL_SPBCGS module
-- Added SUNLINSOL_SPTFQMR module
-- Added SUNLINSOL_PCG module
-- Added SUNNONLINSOL_NEWTON module
-- Added SUNNONLINSOL_FIXEDPOINT module
-- Added NVECTOR_PARALLEL module
-- Added NVECTOR_OPENMP module
-- Added NVECTOR_PTHREADS module
-- Added ARKODE module
-- Added CVODE module
-- Added CVODES module
-- Added IDA module
-- Added IDAS module
-- Added KINSOL module
-- Found PythonInterp: /usr/bin/python (found version "2.7.13")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sundial-build
```

I've had this problem pretty consistently on Debian with a [patched](https://github.com/inria-parkas/sundialsml/blob/master/misc/superlu_mt_3.1.patch) version of SuperLU_MT 3.1. Maybe this isn't the right way to build and install SuperLU_MT? (I always have a lot of trouble with this dependency.)

**Comment by tbrk** [comment]
A `make` in `SUPERLUMT_TEST` gives:
```
/usr/bin/cmake -H/root/sundial-build/SUPERLUMT_TEST -B/root/sundial-build/SUPERLUMT_TEST --check-build-system CMakeFiles/Makefile.cmake 0
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sundial-build/SUPERLUMT_TEST
/usr/bin/cmake -E cmake_progress_start /root/sundial-build/SUPERLUMT_TEST/CMakeFiles /root/sundial-build/SUPERLUMT_TEST/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/root/sundial-build/SUPERLUMT_TEST'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/depend
make[2]: Entering directory '/root/sundial-build/SUPERLUMT_TEST'
cd /root/sundial-build/SUPERLUMT_TEST && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/sundial-build/SUPERLUMT_TEST /root/sundial-build/SUPERLUMT_TEST /root/sundial-build/SUPERLUMT_TEST /root/sundial-build/SUPERLUMT_TEST /root/sundial-build/SUPERLUMT_TEST/CMakeFiles/ltest.dir/DependInfo.cmake --color=
Scanning dependencies of target ltest
make[2]: Leaving directory '/root/sundial-build/SUPERLUMT_TEST'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/build
make[2]: Entering directory '/root/sundial-build/SUPERLUMT_TEST'
[ 50%] Building C object CMakeFiles/ltest.dir/ltest.o
/usr/bin/cc   -I/usr/local/include/superlu_mt  -O3 -DNDEBUG   -o CMakeFiles/ltest.dir/ltest.o   -c /root/sundial-build/SUPERLUMT_TEST/ltest.c
[100%] Linking C executable ltest
/usr/bin/cmake -E cmake_link_script CMakeFiles/ltest.dir/link.txt --verbose=1
/usr/bin/cc  -O3 -DNDEBUG   CMakeFiles/ltest.dir/ltest.o  -o ltest  -L/usr/local/lib -Wl,-rpath,/usr/local/lib -rdynamic -lsuperlu_mt_PTHREAD -lpthread
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dtrsm_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dcopy_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dgemm_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `idamax_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dtrsv_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dgemv_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `dasum_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `daxpy_'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `sqrt'
/usr/local/lib/libsuperlu_mt_PTHREAD.so: undefined reference to `floor'
collect2: error: ld returned 1 exit status
CMakeFiles/ltest.dir/build.make:99: recipe for target 'ltest' failed
make[2]: *** [ltest] Error 1
make[2]: Leaving directory '/root/sundial-build/SUPERLUMT_TEST'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/ltest.dir/all' failed
make[1]: *** [CMakeFiles/ltest.dir/all] Error 2
make[1]: Leaving directory '/root/sundial-build/SUPERLUMT_TEST'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

It works correctly if I manually add `-Iblas` to the `cc` invocation.

**Comment by tbrk** [comment]
The patch can be applied by editing the `Dockerfile`:
```
...
RUN git -c advice.detachedHead=false\
 clone $SUNDIALS_GIT --branch $SUNDIALS_TAG --depth 1 $BUILDDIR/sundials\
 && wget -qO- $SUNDIALSML_SRC/misc/sundials-4.0.2.patch\
	| patch -d $BUILDDIR/sundials -p1\
 && mkdir $BUILDDIR/sundials-build\
 && printf "#!/bin/sh\n\
cmake -Wno-dev \$BUILDDIR/sundials\\\\\n\
...
```

**Comment by gardner48** [comment]
@tbrk the sundials-5.0.0.dev.2 release includes updates to how the SuperLU_MT SUNLinearSolver module is built and should address the problems you were seeing. I'm going to close this PR but if the issue persists please feel free to reopen it or create a new issue.

**Pull request closed without merging**
